### ISSUE TITLE
Pre-trained weights of the GoPro and DVD datasets

### ISSUE THREAD

**Issue by pp00704831** [linjing7/VR-Baseline#10]
Hello,

Do you release the pre-trained weights of the GoPro and DVD datasets?
I want to reproduce your GoPro and DVD results, but you only release the weights called 'FGST.pth', could I reproduce the GoPro and DVD results on 'FGST.pth'?

**Comment by linjing7** [comment]
Hi, thanks for your interest. This work is done during my internship at Huawei and the original pretrained model can not be transferred outside. Therefore, we only retrained our model on GOPRO dataset and obtain 'FGST.pth'. If you have enough GPUs, you can train FGST on DVD dataset.

**Comment by pp00704831** [comment]
Thank you for your reply.  Since I don't have enough GPUs, do you plan to re-train your model on the DVD dataset?

**Comment by linjing7** [comment]
Hi, @pp00704831, I plan to re-train FGST on DVD dataset in December, 2022.
