### ISSUE TITLE
可以提供GOPRO数据集的可视化结果吗

### ISSUE THREAD

**Issue by xuboming8** [linjing7/VR-Baseline#11]
您好，请问可以直接提供GOPRO数据集训练后的可视化结果吗，这里搭环境总是会出问题

**Comment by linjing7** [comment]
您好，感谢您的关注，我们只保存了正文和补充材料出现的图片，放在这个[链接](https://pan.baidu.com/s/1MmoaGdkRomZNHAvGWBYyWg?pwd=5ps3)中，里边包含了FGST及其他对比方法（EDVR, STFAN等）在GOPRO, DVD, Real Blur这三个数据集上的结果，希望对你有帮助～

PS: 因为公司规定，原预训练模型无法外传，所以github提供的预训练模型是在实验室重新训练的，跑出来的视觉结果会跟原图有点区别。后面我们会重新仔细训练，修复这个问题。

**Comment by xuboming8** [comment]
谢谢，里面正好有需要的图片
