### ISSUE TITLE
Hello,if I want to do compression blur, which model should I use? And how should I start training?

### ISSUE THREAD

**Issue by tlovem** [linjing7/VR-Baseline#14]

**Comment by linjing7** [comment]
Hi, thanks for your interest. You need to download the pretrained model and test your own image using the following command:
`python demo/restoration_video_demo.py configs/FGST_deblur_gopro_test.py ${CHKPT} ${IN_PATH} ${OUT_PATH}`
This model is trained on the motion blur dataset and if you want to do compression deblur, you may need to collect your own dataset as GOPRO and retrain your model by:
`bash tools/dist_train.sh configs/FGST_deblur_xxx.py GPU_Nums`

**Comment by tlovem** [comment]
Thank you for your answer, but when I encounter some problems during training, “RuntimeError: cuDNN error: CUDN_ STATUS_ NOT_ INITIALIZED”, is it because my version doesn't correspond?

**Comment by tlovem** [comment]
I followed the steps you provided for training, except that the cuda version is 10.2

**Comment by linjing7** [comment]
Hi, this may be caused by the mismatch between Pytorch and CUDA versions. You need to specify the CUDA version when you install Pytorch.

**Comment by tlovem** [comment]
Thanks for your answer, I'll try again, looking forward to your S2SVR

**Comment by tlovem** [comment]
I reinstalled the pytorch using Conda, which solved the problem just now, but my graphics card doesn't have enough computational power. Can I reduce some parameters to make it work?

**Comment by linjing7** [comment]
Hi, you can try:
1. change the network parameters of FGST, e.g., `dim, dim_emb, num_resblocks`
2. change the training setting, e.g.,  reduce the video length by setting `num_input_frames` to a smaller number, reduce the training iters by setting `total_iters` in the config file.

**Comment by tlovem** [comment]
Thank you for your patient answer. I'll try it
