### ISSUE TITLE
推理结果图片全黑

### ISSUE THREAD

**Issue by sunxiaoyu12** [linjing7/VR-Baseline#17]
命令：python demo/restoration_video_demo.py  ./configs/FGST_deblur_gopro_test.py  ./weights/FGST_gopro.pth  ./data/2.mp4  ./output/

结果如下：
![000000](https://github.com/linjing7/VR-Baseline/assets/38753856/72796302-5af6-4148-aa5a-db53bca0ec32)

**Comment by linjing7** [comment]
你好，可能是train/test代码和demo代码的数据读取不一致导致的，你可以把你的视频处理成跟GoPro一样的格式，然后把FGST_deblur_gopro.py中`lq_folder`和`gt_folder`的路径改为你这个视频路径，再运行`bash tools/dist_train.sh configs/FGST_deblur_gopro_test.py 1`
