### ISSUE TITLE
关于代码的一些相关咨询

### ISSUE THREAD

**Issue by wangweiran0922** [linjing7/VR-Baseline#18]
同学你好，很感谢你对你的工作进行开源。
我有一些问题想咨询一下。
我看代码中关于FGSW-MSA这部分，只有当前帧与前后一帧的光流偏移作为输入。因此想问一下你有试过对2r+1，r≥2帧进行实验吗？实验的结果如何。
还有就是在mmedit/model/backbones/sr_backbones/FGST_util.py中125-145行对前后帧进行的retrive key elements请问这个操作的含义是什么？
如果你能回复我一下，将不胜感激。谢谢。

**Comment by linjing7** [comment]
你好，感谢你的关注！
1. 我们有尝试过r=2的情况，性能能带来一定的提升，但计算量会显著增加，所以我们采用recurrent embedding的方式，以较小的代价，扩大时间维度的感受野。
2. retrive key elements的操作的意思是，根据optical flow vertor，去从相邻帧找到与query最相似的key elements

**Comment by wangweiran0922** [comment]
感谢你的回复，祝好。
