### ISSUE TITLE
可以应用实时视频的去模糊吗

### ISSUE THREAD

**Issue by rookiexiao123** [linjing7/VR-Baseline#21]
您好，请教一下，模型可以应用实时视频的去模糊吗，FPS在25之上。如果现模型复杂度过高不行的话，是否可以修改模型参数，来进行尝试，能否给些指导建议？

**Comment by linjing7** [comment]
你好，我们的模型因为要处理多帧信息，暂时无法应用于实时视频处理。如果要进行实时处理，需要把网络层数和通道数减少，然后重新训练一个模型。

**Comment by rookiexiao123** [comment]
能否推荐一个可以实时视频处理的配置，网络层数，通道数怎么修改，其他参数需要怎么注意修改？

**Comment by linjing7** [comment]
你好，建议dim改为16，每一层的FGAB个数num_FGAB都改为1, num_resblocks也改为1
