### ISSUE TITLE
How to prepare the GoPro dataset?

### ISSUE THREAD

**Issue by Yaofang-Liu** [linjing7/VR-Baseline#4]
Hi. I found that the initial dataset downloaded from the given link doesn't  match the path and indexes you give in VR_Baseline/configs/FGST_deblur_gopro.py.

It raises an error that: FileNotFoundError: [Errno 2] No such file or directory: 'data/GoPro/train/blur/GOPR0868_11_01/00000044.png'.

I wonder what's the specific steps to prepare the data needed? Looking forward to your early reply. Thanks!

**Comment by linjing7** [comment]
Hi, thanks for your interest. We have uploaded the code for data preparing. Please download the newest code and run the following command:
```
cd /VR-Baseline/data_preparation
python GoPro_Util.py --input_path INPUT_PATH --save_path SAVE_PATH
```
You need to replace `INPUT_PATH`  and `SAVE_PATH` with your own path.

**Comment by Yaofang-Liu** [comment]
Works well. Many thanks~
