### ISSUE TITLE
关于configs下面 visual hook的配置

### ISSUE THREAD

**Issue by pokameng** [linjing7/VR-Baseline#5]
原始的代码里面没有对 visual_config配置，默认为none

下面是本人找到的一个模板，仅供参考
inpainting下：
visual_config = dict(
    type='VisualizationHook',
    output_dir='visual',
    interval=10000,
    res_name_list=[
        'gt_img', 'masked_img', 'stage1_fake_res', 'stage1_fake_img',
        'stage2_fake_res', 'stage2_fake_img', 'fake_gt_local'
    ],
)

from  NJUST

**Comment by caiyuanhao1998** [comment]
非常感谢你的建议
