### ISSUE TITLE
关于仓库提供的光流预训练模型的问题

### ISSUE THREAD

**Issue by jeejeelee** [linjing7/VR-Baseline#6]
非常nice的工作，请问[pwc-lite](https://github.com/linjing7/VR-Baseline/blob/main/configs/S2SVR_sr_vimeo.py#L13)的预训练模型是基于S2SVR论文中中描述的无监督训练方式获得的吗？

**Comment by linjing7** [comment]
感谢您的关注，这个工作是在实习期间做的，因为公司规定，之前的预训练模型和代码我们无法传到外边，现在的代码和预训练模型都是重新复现的。S2SVR的pwclite我们暂时使用的是ARFlow提供的预训练模型，这个会导致性能相对差一些。后续我们会开源S2SVR中的无监督光流方法代码及其预训练模型。

**Comment by caiyuanhao1998** [comment]
如果您有机器或者条件的话，也请您帮我们train一下，给个反馈，感谢您

**Comment by jeejeelee** [comment]
谢谢回复，后续我们考虑下能不能train
