### ISSUE TITLE
configs/S2SVR_vqe_mfqev2.py

### ISSUE THREAD

**Issue by kai422** [linjing7/VR-Baseline#7]
Great work! It seems that configs/S2SVR_vqe_mfqev2.py is missing. 
Where can I find that?

**Comment by linjing7** [comment]
Hi, thanks for your interest. Our experiments of the MFQEv2 dataset are based on this [repo](https://github.com/ryanxingql/stdf-pytorch). I'm sorry that this toolbox does not support this dataset yet and I'll include it into our TODO list.

**Comment by kai422** [comment]
I see. Thank you!
