### ISSUE TITLE
What is the {CONFIG} in Testing？

### ISSUE THREAD

**Issue by mioyeah** [linjing7/VR-Baseline#8]

**Comment by linjing7** [comment]
Hi, the testing config is the same as the training one.

**Comment by mioyeah** [comment]
Thank you very much for your answer, and I'm sorry I just saw the mail.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linjing7/VR-Baseline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月15日(星期六) 晚上10:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linjing7/VR-Baseline] What is the {CONFIG} in Testing？ (Issue #8)





 
Closed #8 as completed.
